perl:
  - "5.22"
  - "5.14"
  - "5.10"
before_install: git submodule update --init
install: "make test-deps"
script: "make test"
notifications:
  email:
    - wakaba@suikawiki.org
  irc:
    channels:
      - "irc.suikawiki.org#mechanize"
    use_notice: true
env:
  global:
    secure: "KqYOaPGWIXe30V6iF9qi2xUGhKvVpqEV47IbjPZhQS4HOySRZchbG8QVjoEKVmQrTNppnj5bd6pbSEHw+ijHjQQUEhzCsyOxhgu9o3jylopgSxDd+C4Tg9tiI7uGccX+bOkUHQEoSA3QZk66f/P6eIzO5Gq5XJq51UJaHkV+JR9ULWyQt/4TmzSoJra6zZtJCCzF0zegEwrExTHqc4roniLdW4ZppXIMNv8T++Ksi4GofnK/vGRlJZ9l6sF+BlFy8/bnU0eSHhZ42PsLr2WU+2HW4fyC6sDTfCCbbkfYIlVgnL8jlXa5XNmo0DaAnJO6R0Kaq6ow3Y9gYThNfVti+GqYv70nQIjX4mVLKUSzkjiZdEbmm6e8tVJzvRSKUpaXkfKSP2S8Bjm/xcKkG902/jtMxSAn9/YGXE/1SiBjDotaLxbZa9e0aHvYWqux8oNJ1Dzbsy/L8q2a3+5ElcS1qnxOVzRYnbEZ/D+Poh4NeJoWmzZ2RLg4JjC8CM9aZMTRj4JqbL0xisvIc75zYc0Wqb0hb7PP+0eSyehxYBRRqN3/sN273ufXKLpnqumtWF1/m4qZnBWIyvd7sYPLA4+V7N4xU8XcbhLmAw07wt1Mk1+DLKj4y6H9wJOUygZIxudsgd82FCZHKzWmYFVX2ClXzcxuOsksY5e/VsXqZPHMQQs="
after_success:
  - curl -s -S -L https://gist.githubusercontent.com/wakaba/9970857/raw/travis-merger.pl | perl
