{
   "before_install" : "true",
   "env" : {
      "global" : {
         "secure" : "Om1mW1y\u002BUyC0sZ3IC8L7QlW9kH1f03iT8EUxEaYzDZPFXKBQUWhXVmXxAKpHnRnhr1IrfgdTOixv0G5STrCeJCfqX/wGA0jU2LEMu/zWwcyKBhoYfSHs4EGa/0mtVwnubXMjPKY7CtM5eqQwBwXVWcgI/FO18htZInGePyNtAcCaBGkOuaiRSWYmqkCW86f/MbdTahTHzeQuY8zTjjwWf6BcppXx6ERTQoNbszes6quoHUA9LtWnMW7kESlgsj2SF\u002Bb7bmqfKJ5qD8p7kJDfHZca/SekW1kLRJbZ0d4cj/k1WrR5tjR9w0Ac/lF/xbiH0LHDffyxyQUibMbp9JVhciGOHYYXsnoHM1tHYf58S3y3GTPXgyz5uwgaiNnA0Yhp08WOS1cwvNfbbIqai1DH/wqPYzszGDgZVxtMnAzA6q6aWgJG9AJdqpImAZwUJN5g/ylIcmdXtWK14jFVpj0EWfHJWQ/wc2K88Qu\u002B3CCMXGVaqq3M1xb7sm7zFE\u002BfcK2eVpuWnhYSljb2maqvM615frTslZNR\u002BAtoLbM0Iid/ETkCU7Qi1\u002B8lP3x8VCQngm3JCOX3SM6nI8VrIxu\u002BINNEyGKpwImVqd\u002Bl7ZpOg7gUMaW\u002BkSSjFDsRlryO47DfWGHczMXSAcsAMOCizhkzepOOZj9mJY5B5hDnMl9Gm1YPWD4="
      }
   },
   "git" : {
      "submodules" : false
   },
   "install" : "make test-deps",
   "jobs" : {
      "include" : [
         {
            "before_install" : "true",
            "install" : "true",
            "script" : "curl -f https://gist.githubusercontent.com/wakaba/ab553f86cd017e0cb28c6dbb5364b009/raw/travis-merge-job.pl | perl",
            "stage" : "merge"
         }
      ]
   },
   "language" : "perl",
   "notifications" : {
      "email" : [
         "wakaba@suikawiki.org"
      ],
      "irc" : {
         "channels" : [
            "ircs://irc.suikawiki.org:6697#mechanize"
         ],
         "use_notice" : true
      }
   },
   "perl" : [
      "5.26",
      "5.14",
      "5.10"
   ],
   "script" : "make test"
}
